[package]
name = "plonk-demo-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-plonk = "0.19"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
